package report

import (
	"fmt"
	"io"
	"strings"

	"github.com/wroughtery/quirn/internal/probe"
)

// statusFor returns a human label and a leading emoji for a result's status,
// used by the markdown scorecard.
func statusFor(r probe.Result) (label, emoji string) {
	switch {
	case r.Vulnerable && r.Baselined:
		return "Baselined", "➖"
	case r.Vulnerable:
		return "Vulnerable", "❌"
	case r.Inconclusive:
		return "Inconclusive", "⚠️"
	default:
		return "OK", "✅"
	}
}

// WriteMarkdown renders results as a Markdown scorecard suitable for posting as
// a pull-request comment: a summary line, a per-probe status table, and a
// collapsible evidence block for each new (non-baselined) finding.
func WriteMarkdown(w io.Writer, results []probe.Result, target string) {
	var newFindings, baselined, inconclusive int
	for _, r := range results {
		switch {
		case r.Vulnerable && r.Baselined:
			baselined++
		case r.Vulnerable:
			newFindings++
		case r.Inconclusive:
			inconclusive++
		}
	}

	fmt.Fprintln(w, "## 🛡️ Quirn LLM red-team scorecard")
	fmt.Fprintln(w)
	if target != "" {
		fmt.Fprintf(w, "**Target:** `%s`\n\n", target)
	}

	p := Score(results)
	fmt.Fprintf(w, "**Posture: %s — %d/100** (%s)\n\n", p.Letter, p.Score, p.Reason)

	var verdict string
	switch {
	case newFindings > 0:
		verdict = fmt.Sprintf("❌ **%d new %s found.**", newFindings, plural(newFindings, "vulnerability", "vulnerabilities"))
	case len(results) > 0 && newFindings == 0 && baselined == 0 && inconclusive == len(results):
		// Every probe failed to reach a verdict: nothing was actually tested, so
		// this is not a clean pass. Say so instead of a misleading green banner.
		verdict = "⚠️ **No verdict reached — every probe was inconclusive.** The target may be unreachable, unauthorized, or too slow; results below are not a pass."
	default:
		verdict = "✅ **No new vulnerabilities found.**"
	}
	fmt.Fprintln(w, verdict)
	fmt.Fprintln(w)
	fmt.Fprintf(w, "%d probe(s) run — %d new, %d baselined, %d inconclusive.\n\n",
		len(results), newFindings, baselined, inconclusive)

	fmt.Fprintln(w, "| Probe | OWASP | Severity | Status |")
	fmt.Fprintln(w, "|---|---|---|---|")
	for _, r := range results {
		label, emoji := statusFor(r)
		// The graded indirect-injection probe carries a resistance tier; show it
		// after the status so the scorecard ranks robustness even when every row
		// is "safe". Ungraded probes have an empty Grade and read unchanged.
		if r.Grade != "" {
			label += " `" + r.Grade + "`"
		}
		fmt.Fprintf(w, "| %s | %s | %s | %s %s |\n",
			mdEscape(r.Name), r.OWASP, r.Severity, emoji, label)
	}
	fmt.Fprintln(w)

	// Evidence only for new findings — baselined ones are already accepted and
	// safe on-task probes carry no actionable detail.
	shown := false
	for _, r := range results {
		if !r.Vulnerable || r.Baselined {
			continue
		}
		if !shown {
			fmt.Fprintln(w, "### Findings")
			fmt.Fprintln(w)
			shown = true
		}
		fmt.Fprintf(w, "<details><summary><strong>%s</strong> (%s, %s)</summary>\n\n",
			mdEscape(r.Name), r.OWASP, r.Severity)
		fmt.Fprintln(w, "```")
		fmt.Fprintln(w, strings.TrimRight(r.Evidence, "\n"))
		fmt.Fprintln(w, "```")
		fmt.Fprintln(w, "</details>")
		fmt.Fprintln(w)
	}

	fmt.Fprintln(w, "<sub>Generated by [quirn](https://github.com/wroughtery/quirn) — OWASP LLM Top 10 red-team.</sub>")
}

func plural(n int, singular, pluralForm string) string {
	if n == 1 {
		return singular
	}
	return pluralForm
}

// mdEscape escapes the pipe character so probe names can't break table layout.
func mdEscape(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
